[package]
name = "pi25"
version = "1.0.0"
authors = ["Mick Koch <mick@kochm.co>"]

[dependencies]

clap = "^2.12.1"
collect_slice = "^1.0.0"
demod_fm = {version = "^1.0.0", path = "../demod_fm"}
fnv = "^1.0.5"
imbe = {version = "^1.0.0", path = "../imbe"}
libc = "^0.2.8"
map_in_place = {version = "^1.0.0", path = "../map_in_place"}
num = "^0.1.34"
p25 = {version = "^1.0.0", path = "../p25"}
p25_filts = {version = "^1.0.0", path = "../p25_filts"}
pi25_cfg = {version = "^1.0.0", path = "../pi25_cfg"}
pool = {version = "^0.1.3", path = "../pool"}
prctl = {version = "^1.0.0", path = "../prctl-rs"}
rand = "^0.3.13"
rtlsdr = {version = "^1.0.0", path = "../rtlsdr"}
rtlsdr_iq = {version = "^1.0.0", path = "../rtlsdr_iq"}
sigpower = {version = "^1.0.0", path = "../sigpower"}
static_decimate = {version = "^1.0.0", path = "../static_decimate"}
static_fir = {version = "^1.0.0", path = "../static_fir"}
throttle = {version = "^1.0.0", path = "../throttle"}
xdg-basedir = "^1.0.0"
