[package]
name = "recv-p25"
version = "1.0.0"
authors = ["Mick Koch <mick@kochm.co>"]

[dependencies]
arrayvec = "0.3.12"
byteorder = "0.3.13"
byteorder_iter = {version = "1.0.0", path = "../byteorder_iter"}
cfg = {version = "1.0.0", path = "../cfg"}
collect_slice = "1.0.0"
dsp = {version = "1.0.0", path = "../dsp"}
imbe = {version = "1.0.0", path = "../imbe"}
libc = "0.2.8"
map_in_place = {version = "1.0.0", path = "../map_in_place"}
num = "0.1.30"
p25 = {version = "1.0.0", path = "../p25"}
pool = {version = "0.1.3", path = "../pool"}
rand = "0.3.13"
rtlsdr = {version = "1.0.0", path = "../rtlsdr"}
sigpower = {version = "1.0.0", path = "../sigpower"}
ui = {version = "1.0.0", path = "../ui"}
xdg-basedir = "0.2.2"
prctl = {version = "1.0.0", path = "../prctl-rs"}

[[bin]]
name = "recv"

[[bin]]
name = "sdr"
