version: 2.1
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: |
          apt update
          apt install librtlsdr-dev
          cargo build
          cargo rustc --release -- -C target-cpu=native -C lto
