version: 2.1
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: |
          apt update
          apt install -y librtlsdr-dev
          cargo test
          cargo build
          cargo rustc --release -- -C target-cpu=native -C lto

workflows:
  version: 2
  workflow:
    jobs:
      - build

  check_latest:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
